### ISSUE TITLE
Memory overload!

### ISSUE THREAD

**Issue by ihamadfuad** [Abedalkareem/LanguageManager-SwiftUI#1]
Hello!

Have a look at this:

<img width="610" alt="Screen Shot 2021-11-25 at 3 38 26 PM" src="https://user-images.githubusercontent.com/20824376/143453222-fa20c641-fbc0-4466-8261-50ec5b257753.png">

P.S: It keeps increasing by 2 mb/s

**Comment by Abedalkareem** [comment]
Are you getting this just by running the example? I tried the example project and I can't see any issue.
If you can share more information about how to reproduce I'll be happy to help!

Thanks,

**Comment by Abedalkareem** [comment]
Closing this, please if you find that there is an issue you can create a new one.
