### ISSUE TITLE
LanguageManagerView's initializer gets called recursively

### ISSUE THREAD

**Issue by UmairSharif** [Abedalkareem/LanguageManager-SwiftUI#3]
In my app, I have to support English and Arabic. Implemented this library and everything is working fine.
Until there comes a Modally presented view i.e. using **.fullScreenCover** 

As modally presented view contains its own navigation stack I have to wrap its body content with 
**LanguageManagerView(.deviceLanguage)** but it creates an infinite loop of LanguageManagerView's initializer and I cannot perform any action on this screen.

I'm still trying to figure out what creates that loop.

```
var body: some View {
    LanguageManagerView(.deviceLanguage) {
        NavigationView {...}
    }
}
```

**Comment by Abedalkareem** [comment]
I just tried the same example you mentioned and it's working fine. I'm closing this issue and if you still face this issue please one another issue with a full example of how to reproduce it so I can help.

Thank you for your contribution!
